version: "3"
services:
  api:
    image: demo4
    container_name: my-name
    ports:
    - 3004:3004
    volumes:
    - data:/opt/app/data
    networks:
    - myNetwork

    
networks:
  myNetwork:
    driver: bridge

volumes:
  data: {}



# if we have network myNetwork and connect to it
#networks:
#  default:
#    external: true
#    name: myNetwork

    